create table if not exists public.guestbook_messages (
  id bigint generated by default as identity primary key,
  display_name text not null check (char_length(trim(display_name)) between 2 and 40),
  message text not null check (char_length(trim(message)) between 4 and 300),
  is_approved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists guestbook_messages_public_idx
  on public.guestbook_messages (created_at desc)
  where is_approved = true;

alter table public.guestbook_messages enable row level security;

drop policy if exists "Public can read approved guestbook messages" on public.guestbook_messages;
create policy "Public can read approved guestbook messages" on public.guestbook_messages
  for select to anon, authenticated using (is_approved = true);

drop policy if exists "Public can submit guestbook messages" on public.guestbook_messages;
create policy "Public can submit guestbook messages" on public.guestbook_messages
  for insert to anon, authenticated with check (
    is_approved = false
    and char_length(trim(display_name)) between 2 and 40
    and char_length(trim(message)) between 4 and 300
  );

grant select, insert on public.guestbook_messages to anon, authenticated;
grant usage, select on sequence public.guestbook_messages_id_seq to anon, authenticated;
