create table if not exists public.tracks (
  id text primary key,
  title text not null,
  artist text not null default 'SmartPioneer',
  album text not null default 'SmartPioneer Music',
  file_path text not null unique,
  duration_seconds numeric(8,2),
  track_number integer not null,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.play_events (
  id bigint generated by default as identity primary key,
  track_id text not null references public.tracks(id) on delete cascade,
  session_id uuid not null,
  listened_seconds integer not null default 0 check (listened_seconds >= 0),
  played_at timestamptz not null default now()
);

create index if not exists play_events_track_played_idx
  on public.play_events (track_id, played_at desc);

create table if not exists public.playlists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  created_at timestamptz not null default now()
);

create table if not exists public.playlist_tracks (
  playlist_id uuid not null references public.playlists(id) on delete cascade,
  track_id text not null references public.tracks(id) on delete cascade,
  position integer not null default 0,
  added_at timestamptz not null default now(),
  primary key (playlist_id, track_id)
);

create table if not exists public.likes (
  user_id uuid not null references auth.users(id) on delete cascade,
  track_id text not null references public.tracks(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, track_id)
);

alter table public.tracks enable row level security;
alter table public.play_events enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_tracks enable row level security;
alter table public.likes enable row level security;

drop policy if exists "Public can read published tracks" on public.tracks;
create policy "Public can read published tracks" on public.tracks
  for select to anon, authenticated using (is_published = true);

drop policy if exists "Public can record valid plays" on public.play_events;
create policy "Public can record valid plays" on public.play_events
  for insert to anon, authenticated with check (
    listened_seconds between 0 and 86400
    and exists (
      select 1 from public.tracks
      where tracks.id = play_events.track_id and tracks.is_published = true
    )
  );

drop policy if exists "Users manage own playlists" on public.playlists;
create policy "Users manage own playlists" on public.playlists
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage tracks in own playlists" on public.playlist_tracks;
create policy "Users manage tracks in own playlists" on public.playlist_tracks
  for all to authenticated
  using (exists (select 1 from public.playlists p where p.id = playlist_id and p.user_id = auth.uid()))
  with check (exists (select 1 from public.playlists p where p.id = playlist_id and p.user_id = auth.uid()));

drop policy if exists "Users manage own likes" on public.likes;
create policy "Users manage own likes" on public.likes
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.get_track_play_counts()
returns table (track_id text, play_count bigint)
language sql
stable
security definer
set search_path = public
as $$
  select t.id, count(e.id)
  from public.tracks t
  left join public.play_events e on e.track_id = t.id
  where t.is_published = true
  group by t.id;
$$;

revoke all on function public.get_track_play_counts() from public;
grant execute on function public.get_track_play_counts() to anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select on public.tracks to anon, authenticated;
grant insert on public.play_events to anon, authenticated;
grant select, insert, update, delete on public.playlists to authenticated;
grant select, insert, update, delete on public.playlist_tracks to authenticated;
grant select, insert, delete on public.likes to authenticated;
grant usage, select on sequence public.play_events_id_seq to anon, authenticated;

insert into public.tracks (id, title, artist, album, file_path, duration_seconds, track_number, is_featured)
values
  ('detak-jantung-koin-pi', 'Detak Jantung Koin Pi', 'SmartPioneer', 'SmartPioneer Music', '01-detak-jantung-koin-pi.mp3', 183.60, 1, false),
  ('doktor-nicolas-versi-2', 'Doktor Nicolas (Versi 2)', 'SmartPioneer', 'SmartPioneer Music', '02-doktor-nicolas-versi-2.mp3', 206.76, 2, false),
  ('golden-opportunity', 'Golden Opportunity', 'SmartPioneer', 'SmartPioneer Music', '03-golden-opportunity.mp3', 135.00, 3, false),
  ('koin-pi-aliran-kemajuan-bangsa-revamp', 'Koin Pi: Aliran Kemajuan Bangsa (Revamp)', 'SmartPioneer', 'SmartPioneer Music', '04-koin-pi-aliran-kemajuan-bangsa-revamp.mp3', 233.84, 4, false),
  ('nada-pioneer', 'Nada Pioneer', 'SmartPioneer', 'SmartPioneer Music', '05-nada-pioneer.mp3', 215.44, 5, true),
  ('pi-menuju-harapan-cover-female', 'Pi Menuju Harapan (Cover Female)', 'SmartPioneer', 'SmartPioneer Music', '06-pi-menuju-harapan-cover-female.mp3', 221.08, 6, false),
  ('pi-network-mugen-tsukuyomi', 'Pi Network 無限月読', 'SmartPioneer', 'SmartPioneer Music', '07-pi-network-mugen-tsukuyomi.mp3', 282.60, 7, false),
  ('pi-network-impian-tanpa-batas', 'Pi Network: Impian Tanpa Batas', 'SmartPioneer', 'SmartPioneer Music', '08-pi-network-impian-tanpa-batas.mp3', 219.96, 8, false),
  ('pioneer-to-the-moon', 'Pioneer To The Moon', 'SmartPioneer', 'SmartPioneer Music', '09-pioneer-to-the-moon.mp3', 199.92, 9, false),
  ('sebuah-ramalan-revamp', 'Sebuah Ramalan (Revamp)', 'SmartPioneer', 'SmartPioneer Music', '10-sebuah-ramalan-revamp.mp3', 216.92, 10, false),
  ('tabungan-rakyat-revamp', 'Tabungan Rakyat (Revamp)', 'SmartPioneer', 'SmartPioneer Music', '11-tabungan-rakyat-revamp.mp3', 234.16, 11, false),
  ('the-wheel-of-life-is-always-turning-revamp', 'The Wheel of Life is Always Turning (Revamp)', 'SmartPioneer', 'SmartPioneer Music', '12-the-wheel-of-life-is-always-turning-revamp.mp3', 194.44, 12, false)
on conflict (id) do update set
  title = excluded.title,
  artist = excluded.artist,
  album = excluded.album,
  file_path = excluded.file_path,
  duration_seconds = excluded.duration_seconds,
  track_number = excluded.track_number,
  is_featured = excluded.is_featured,
  is_published = true;
